package bean;
// Generated 17/09/2023 12:32:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GenerosVc generated by hbm2java
 */
@Entity
@Table(name="generos_vc"
    ,catalog="db_vivian_carvalho"
)
public class GenerosVc  implements java.io.Serializable {


     private int idgenerosVc;
     private String nomeVc;
     private String descricaoVc;
     private String anoOrigemVc;
     private String notasVc;
     private String generosVccol;

    public GenerosVc() {
    }

    public GenerosVc(int idgenerosVc, String nomeVc, String descricaoVc, String anoOrigemVc, String notasVc, String generosVccol) {
       this.idgenerosVc = idgenerosVc;
       this.nomeVc = nomeVc;
       this.descricaoVc = descricaoVc;
       this.anoOrigemVc = anoOrigemVc;
       this.notasVc = notasVc;
       this.generosVccol = generosVccol;
    }
   
     @Id 

    
    @Column(name="idgeneros_vc", unique=true, nullable=false)
    public int getIdgenerosVc() {
        return this.idgenerosVc;
    }
    
    public void setIdgenerosVc(int idgenerosVc) {
        this.idgenerosVc = idgenerosVc;
    }

    
    @Column(name="nome_vc", nullable=false, length=45)
    public String getNomeVc() {
        return this.nomeVc;
    }
    
    public void setNomeVc(String nomeVc) {
        this.nomeVc = nomeVc;
    }

    
    @Column(name="descricao_vc", nullable=false, length=45)
    public String getDescricaoVc() {
        return this.descricaoVc;
    }
    
    public void setDescricaoVc(String descricaoVc) {
        this.descricaoVc = descricaoVc;
    }

    
    @Column(name="ano_origem_vc", nullable=false, length=45)
    public String getAnoOrigemVc() {
        return this.anoOrigemVc;
    }
    
    public void setAnoOrigemVc(String anoOrigemVc) {
        this.anoOrigemVc = anoOrigemVc;
    }

    
    @Column(name="notas_vc", nullable=false, length=45)
    public String getNotasVc() {
        return this.notasVc;
    }
    
    public void setNotasVc(String notasVc) {
        this.notasVc = notasVc;
    }

    
    @Column(name="generos_vccol", nullable=false, length=45)
    public String getGenerosVccol() {
        return this.generosVccol;
    }
    
    public void setGenerosVccol(String generosVccol) {
        this.generosVccol = generosVccol;
    }




}


